mywww/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cv/', include('resume.urls')),
    path('production/', include('production.urls', namespace='production')),
    path('', home),
    
            ]

production/urls.py
from django.urls import path
from . import views

app_name = 'production'

urlpatterns = [

    path('', views.production, name = 'production'),
    #REPORT
    path('report/', views.report_shift, name = 'report'),
    path('report/<int:n_shift>/', views.report_view, name = 'report_shift'),
    path('report/list/', views.report_list, name = 'report_list'),
    #HOLIDAY REQUEST
    path('holiday_request/',views.holiday_request, name = 'holiday_request'),
    path('holiday_request/<int:request_id>/', views.h_request_pdf, name = 'h_request_pdf'),
    path('report/list/<str:day_1>/<str:day_2>/', views.report_list_pdf, name = 'report_list_pdf'),
    #TASK
    path('task_list/', views.task_list, name = 'task_list'),
    path('task_list/done/<str:pk>/', views.done_task, name = 'done_task'),
    path('task_list/delete/<str:pk>/', views.delete_task, name = 'delete_task'),
    path('done_today/', views.task_done_today, name = 'task_done_today'),
    path('done_last_week/', views.task_done_last_week, name = 'task_done_last_week'),
    #API
    path('api/', views.apioverview, name = 'api_view'),
    path('api/report-list/', views.reports_api, name = 'api_reports'),
    path('api/report-list/<str:pk>/', views.single_report_api, name = 'single_api_report'),
    path('api/report-list-json/', views.reports_api_json, name = 'api_reports_json'),
    path('api/report-list-json/<str:pk>/', views.single_report_api_json, name  =  'single_api_report_json'),
    path('api/redis-json/', views.redis_dict_json, name  =  'redis_dict_json'),
            ]

resume/urls.py
from django.urls import path
from . import views

app_name = 'resume'

urlpatterns = [
    path('', views.home, name='home'),
    path('about_me/', views.about_me, name='about_me'),
    path('education/', views.education, name='education'),
    path('expirience/', views.expirience, name='expirience'),
    path('website/', views.website, name='website'),
    path('contact/', views.contact, name='contact'),
    path('skills/', views.skills, name = 'skills'),
    path('back-end/', views.back, name = 'back'),
    path('skills/<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name = 'blog_detail'),
    path('skills/tag/<slug:tag_slug>/', views.skills, name='post_list_by_tag'),
    path('api/', views.api_list, name='api_list'),

    

            ]

production/models.py
from django.db import models
from django.utils import timezone
from ckeditor.fields import RichTextField 


TODAY = timezone.now().date()
DEPARTMENTS = ((1,'Electrical'),(2,'IT'),(3,'Bookkeeping'),(4,'Production'))
LIST_SHIFT = (('1','Shift_1'),('2','Shift_2'),('3','Shift_3'))
LIST_TEAM = (('1','Team_1'),('2','Team_2'),('3','Team_3'),('4','Team_4'))
LIST_QUANITY =[(i, str(i)) for i in range(0, 21)]


class Report(models.Model):

    shift = models.CharField(choices = LIST_SHIFT, max_length=10,unique_for_date = 'created')
    team = models.CharField(choices = LIST_TEAM, max_length = 10, default = '1')
    product_A = models.PositiveIntegerField(default = 0, choices = LIST_QUANITY)
    product_B = models.PositiveIntegerField(default = 0, choices = LIST_QUANITY)
    description = models.TextField(max_length = 500, blank = False, null = False)
    created = models.DateField(default = timezone.now,db_index= True) 

    class Meta:
        ordering =('created','-shift')
    
    def __str__(self):
        return '{} {} {}'.format(self.shift, self.team, self.created)

class Holiday_request(models.Model):

    first_name = models.CharField(max_length = 20,blank = False, null = False)
    surname = models.CharField(max_length = 20,blank = False, null = False)
    email = models.EmailField(blank = False, null = False)
    department = models.PositiveIntegerField(choices = DEPARTMENTS, blank = False, null = False)
    date_begin = models.DateField(default = TODAY)
    date_end = models.DateField(default = TODAY)
    notice = RichTextField(max_length = 500,blank = False, null = False)
    created = models.DateField(auto_now_add = True)
    approved = models.BooleanField(default = False)

    class Meta:
        ordering = ('-created',)
    
    def __str__(self):
        return  " {} {}  from {} to {} ".format(self.first_name, self.surname, self.date_begin, self.date_end)


class Task(models.Model):
    title = models.CharField(max_length = 150)
    done = models.BooleanField(default = False)
    created = models.DateField(auto_now_add = True,db_index=True)
    time = models.TimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-created',)

class Info(models.Model):
    title = models.CharField(max_length=25)
    created = models.DateField(auto_now_add=True,db_index=True)
    time = models.TimeField(auto_now_add = True)

    def __str__(self):
        return "{} {} {}".format(self.created, self.time, self.title)

production/forms.py
from django import forms
from .models import Report, Holiday_request, Task
from django.contrib.admin import widgets 
from django.forms.widgets import NumberInput
from django.utils import timezone

TODAY = timezone.now().date()
BEGIN = timezone.datetime(2021,1,1).date()

class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ('team','product_A','product_B','description')


class DayForm(forms.Form):
    day_1 = forms.DateField(label='Begin',initial = BEGIN,widget=NumberInput(attrs={'type': 'date'}))
    day_2 = forms.DateField(label='End',initial = TODAY,widget=NumberInput(attrs={'type': 'date'}))


class HolidayForm(forms.ModelForm):
    class Meta:
        model = Holiday_request
        fields = ('first_name','surname','email','department','date_begin','date_end','notice')
        widgets = { 'date_begin': NumberInput( attrs={'type': 'date'}),
                    'date_end': NumberInput(attrs={'type': 'date'}),
                     }

class TaskForm(forms.Form):
    title =forms.CharField(max_length=150,label="Creata a new task")

    
    

production/views.py
from django.shortcuts import render, get_object_or_404, redirect, get_list_or_404
from django.urls import reverse
from .models import Report, Holiday_request, Task, Info
from .forms import ReportForm, DayForm, HolidayForm, TaskForm
from datetime import date
from datetime import timedelta
from django.db.models import Sum
from django.utils import timezone
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import render_to_string
import weasyprint
from django.http import JsonResponse
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .serializers import ReportSerializer
import redis 

r = redis.StrictRedis(host='localhost',port=6379,db=0)


TODAY = timezone.now().date()
WEEK = timezone.timedelta(days=7)
WEEK_AGO = TODAY - WEEK



def report_view(request,n_shift=1):
    if n_shift not in [1,2,3]:
        return redirect(reverse('production:report_shift'))
    template = 'report.html'
    if request.method == 'POST':
        check_quantity=len(Report.objects.all().filter(created=TODAY,shift=n_shift))
        report_form = ReportForm(data = request.POST)  
        if report_form.is_valid() and check_quantity == 0:
            report=report_form.save(commit = False)
            report.shift=n_shift
            report.save()
            context={'new':True}
            return render(request,template,context)
        elif report_form.is_valid() and check_quantity == 1:
            report=get_object_or_404(Report, created=TODAY,shift=n_shift)
            report.delete()
            report=report_form.save(commit = False)
            report.shift=n_shift
            report.save()
            context={'updated':True}
            return render(request,template,context)
    else:
        report_form = ReportForm()
    context = {'report_form':report_form,'n_shift':n_shift}
    Info.objects.create(title='report_view')
    return render(request,template,context)

def report_shift(request):
    template='report_shift.html'
    context={}
    Info.objects.create(title='report_shift')
    return render(request,template,context)


def report_list(request):
    if request.method=='POST':
        form=DayForm(data=request.POST)
        if form.is_valid():
            cd=form.cleaned_data
            try:
                day1, day2 = cd['day_1'],cd['day_2']
                report_list = Report.objects.all().filter(created__gte=day1,created__lte=day2)
                number_of_records=len(report_list)
            except:
                return redirect(reverse('production:report_list'))
        else:
            return redirect(reverse('production:report_list'))
    else:   
        day1, day2 = WEEK_AGO,TODAY
        report_list=Report.objects.all().filter(created__gte=day1, created__lte=day2)
        number_of_records = len(report_list) 
    sum_product_A = report_list.aggregate(Sum('product_A'))
    sum_A = sum_product_A['product_A__sum']
    sum_product_B = report_list.aggregate(Sum('product_B'))
    sum_B = sum_product_B['product_B__sum']
    template = 'report_list.html'
    context = {'report_list':report_list,
                'form':DayForm,
                'number_of_records':number_of_records,
                'sum_A':sum_A,'sum_B':sum_B,
                'day_1':day1,'day_2':day2}
    Info.objects.create(title='report_list')
    return render(request,template, context)


def holiday_request(request):
    if request.method == 'POST':
        forms = HolidayForm(data=request.POST)
        if forms.is_valid():
            forms.save()
            number_request = Holiday_request.objects.latest('id')           
            context = { 'forms': forms,'POST':'POST','number_id':number_request.id}        
    else:   
        forms = HolidayForm()
        context = { 'forms': forms }
    template = 'Holiday_request.html'
    Info.objects.create(title='holiday_request')
    return render(request,template,context)

def production(request):
    template = "production.html"
    context = {}
    return render(request,template,context)


def h_request_pdf(request, request_id):
    h_request = get_object_or_404(Holiday_request, id=request_id)
    html = render_to_string('pdf_dir/template_pdf.html',{'h_request': h_request})
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'filename="h_request_{}.pdf"'.format(h_request.id)
    weasyprint.HTML(string=html).write_pdf(response, stylesheets=[weasyprint.CSS(settings.PDF_CSS)])
    Info.objects.create(title='h_request_pdf')
    return response


def report_list_pdf(request, day_1,day_2):
    report_list = Report.objects.all().filter(created__gte=day_1,created__lte=day_2)
    sum_product_A = report_list.aggregate(Sum('product_A'))
    sum_A = sum_product_A['product_A__sum']
    sum_product_B = report_list.aggregate(Sum('product_B'))
    sum_B = sum_product_B['product_B__sum']
    context = {'report_list': report_list,
                'sum_product_A':sum_A,
                'sum_product_B':sum_B,
                'number_of_records':len(report_list) }
    html = render_to_string('pdf_dir/template_pdf_table.html',context)
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'filename="report_list.pdf"'
    weasyprint.HTML(string=html).write_pdf(response, stylesheets=[weasyprint.CSS(settings.PDF_CSS)])
    Info.objects.create(title='report_list_pdf')
    return response


def task_list(request):
    template = 'task_list.html'
    task_list = Task.objects.filter(done=False,created=TODAY)
    if request.method == "POST":
        task_form = TaskForm(data = request.POST)
        if task_form.is_valid():
            cd = task_form.cleaned_data
            Task.objects.create(title=cd['title'])
    else:
        task_form = TaskForm()
    context = {'task_list': task_list, 'task_form':task_form}
    Info.objects.create(title='task_list')
    return render(request, template, context)

def done_task(request,pk):
    task = get_object_or_404(Task, id=pk)
    task.done = True
    task.save()
    Info.objects.create(title='done_task')
    return redirect("production:task_list")

def delete_task(request,pk):
    task = get_object_or_404(Task, id=pk)
    task.delete()
    Info.objects.create(title='delete_task')
    return redirect("production:task_list")

def task_done_today(request):
    template = 'task_list_done.html'
    task_list = Task.objects.filter(done=True, created=TODAY)
    context = {'task_list': task_list,'TODAY':TODAY}
    Info.objects.create(title='task_done_today')
    return render(request, template, context)

def task_done_last_week(request):
    template = 'task_list_done.html'
    task_list = Task.objects.filter(done=True, created__gte=WEEK_AGO, created__lte=TODAY)
    context = {'task_list': task_list,}
    Info.objects.create(title='task_done_last_week')
    return render(request, template, context)

@api_view(['GET'])
def apioverview(request):
    word="data"
    return Response(word)


@api_view(['GET'])
def reports_api(request):
    reports = Report.objects.all()[:50]
    serializers = ReportSerializer(reports, many=True )
    return Response(serializers.data)

@api_view(['GET'])
def single_report_api(request,pk):
    reports = Report.objects.get(id=pk)
    serializers = ReportSerializer(reports, many=False)
    return Response(serializers.data)

@api_view(['GET'])
def reports_api_json(request):
    reports = Report.objects.all()[:50]
    serializers = ReportSerializer(reports, many=True )
    return JsonResponse(serializers.data)

@api_view(['GET'])
def single_report_api_json(request,pk):
    reports = Report.objects.get(id=pk)
    serializers = ReportSerializer(reports, many=False)
    return JsonResponse(serializers.data)

@api_view(['GET'])
def redis_dict_json(request):
    keys = r.keys()
    dict1 = {}
    for i in keys:
        a = i.decode('utf-8')
        if str(TODAY) in a:       
            b = r.get(i).decode('utf-8')
            dict2 = {a:int(b)}
            dict1.update(dict2)

    return JsonResponse(dict1)

production/templates/Holiday_request.html
{% extends "base_pro.html" %}
{% block title %}HOLIDAY REQUEST{% endblock %}
{% block content %}
{% if POST %}
<h1>Your request has been send</h1>
<br> 
<h3 style="text-align: center;"><a href="{% url "production:h_request_pdf" number_id %}">Download PDF file</a></h3>
{% else %}
<form action = "." method = "POST">
    {{ forms.as_p }}
    {{ forms.media }}
    {% csrf_token %}
<input type="submit" value="Send and make a pdf file">
{% endif %}
{% endblock %}

production/templates/base_pro.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<link href="{% static "css/pro.css" %}" rel="stylesheet">
<title>{% block title %}{% endblock %}</title>
</head>
<body>
<ul>
    <li><a href="{% url "production:production" %}">Home</a></li>
    <li><a href="{% url "production:report" %}">Make a report</a></li>
    <li><a href="{% url "production:report_list" %}">Report list</a></li>
    <li><a href="{% url "production:holiday_request" %}">Holiday Request</a></li>
    <li><a href="{% url "production:task_list" %}">Task list</a></li>
    <li style="float: right;"><a href="{% url "resume:home" %}">Return</a></li>
</ul>
<br><br><br>
<div class="styl1">
{% block content %}
{% endblock %} 
</div>
</body>
</html>

production/templates/production.html
{% extends "base_pro.html" %}
{% block title %}Production{% endblock %}
{% block content %}
<p style="text-align: center;">
<strong>
<span style="font-size: 28px;">
<strong>This page includes</strong>
</span>
</strong>
</p>
<p style="text-align: center;"><strong><br></strong>
<strong><span style="font-size: 22px;">
<strong>Entering reports of each shift<br>
Readout of all completed reports<br>
Convert reports to PDF file<br>
To fill in a vacation application and print a PDF<br>
TO DO LIST applications
</strong>
</span>
</strong>
</p>
{% endblock %}

production/templates/report.html
{% extends "base_pro.html" %}

{% block title %}
REPORT
{% endblock %}
{% block content %}
{% if new %}
Report has send
{% elif updated %}
the report has been saved
{% else %}
{% if n_shift == 1 %} <h1 style="color: rgb(255, 255, 255)">SHIFT 1</h1> {% endif %}
{% if n_shift == 2 %} <h1 style="color: black">SHIFT 2</h1>  {% endif %}
{% if n_shift == 3 %} <h1 style="color: yellow">SHIFT 3</h1>  {% endif %}
<form action="." method="post">
    {{ report_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Send"></p>
</form>
{% endif %}
</body>
</html>
{% endblock %}

production/templates/report_list.html
{% extends "base_pro.html" %}

{% block title %} REPORT LIST {% endblock %}

{% block content %}
{% if form %}
<h2>Number of records {{ number_of_records }}</h2>

<h2>Sum of product_A {{sum_A}}</h2>

<h2>Sum of product_B {{sum_B}}</h2>
<form action ="." method= "post">
  {{ form.as_p }}
  {% csrf_token %}
  <input type="submit" value="Send">
</form>
{% endif %}
<a href="{% url 'production:report_list_pdf' day_1 day_2 %}" target="_blank">Create a pdf file</a>
    <table>
        <thead>
        <tr>
        <th>Date</th>
        <th>Shift</th>
        <th>Team</th>
        <th>Product_A</th>
        <th>Product_B</th>
        </tr>
        </thead>
        <tbody>
         <h4>   
        {% for report in report_list %} 
        <tr>
        <td><i>{{ report.created }}</i></td>
        <td>{{ report.shift }}</td>
        <td>{{ report.team}}</td>
        <td>{{ report.product_A }}</td>
        <td>{{ report.product_B }}</td>
        {% endfor %}
        </h4>
    </table>
{% endblock %}

production/templates/report_shift.html
{% extends "base_pro.html" %}
{% block title %}
REPORT SHIFT
{% endblock %}
{% block content %}
<h1>Report SHIFT</h1>
<h2 ><a style="color: rgb(255, 255, 255)" href="{% url "production:report_shift" 1 %}">SHIFT 1</a></h2>
<h2 ><a style="color: rgb(0, 0, 0)" href="{% url "production:report_shift" 2 %}">SHIFT 2</a></h2>
<h2 ><a style="color: rgb(229, 255, 0)" href="{% url "production:report_shift" 3 %}">SHIFT 3</a></h2>
{% endblock %}

production/templates/task_list.html
{% extends "base_pro.html" %}
{% block title %} Task List {% endblock %}
{% block content %}
<ul>
<li><a href="{% url "production:task_list" %}">Task list</a></li>
<li><a href="{% url "production:task_done_today" %}">Task done today</a></li>
<li><a href="{% url "production:task_done_last_week" %}">Task done last week</a></li>
</ul>
<br><br>
<form action="." method="POST">
    {{ task_form.as_table }}
    {% csrf_token %}
    <br>
    <input type="submit" value="OK">
</form>
<br>
<div >
{% for task in task_list %}
<div class="style2">

<ul>
    <li><a style="background-color: #0F88F2;">{{ task.title }}</a></li>
    <li style="float: right;"><a href="{% url "production:done_task" task.id   %}">DONE &#9989</a></li>
    <li style="float: right;"><a href="{% url "production:delete_task" task.id   %}">DELETE &#10060</a></li>
    <li style="float: right;"><a style="background-color: #0F88F2;">{{ task.time }}</a></li>
</ul>
<br>


{% endfor %}
</div>
{% endblock %}

production/templates/task_list_done.html
{% extends "base_pro.html" %}
{% block title %} Task Done Today {% endblock %}
{% block content %}
<ul>
<li><a href="{% url "production:task_list" %}">Task list</a></li>
<li><a href="{% url "production:task_done_today" %}">Task done today</a></li>
<li><a href="{% url "production:task_done_last_week" %}">Task done last week</a></li>
</ul>
<br><br>
<br>
<div >
{% for task in task_list %}
<div class="style2">

<ul>
    <li style="float: left;"><a style="font-weight: bold;">{{ task.title }}  &#9989 </a></li>
    <li style="float: right;"><a> {% if task.created != TODAY %} {{ task.created }} &nbsp;&nbsp; {% endif %}{{ task.time }} </a></li>
    <li style="float: right;"><a>DONE</a></li>
</ul>
<br>


{% endfor %}
</div>
{% endblock %}