mywww/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cv/', include('resume.urls')),
    path('production/', include('production.urls', namespace='production')),
    path('', home),
    
            ]

production/urls.py
from django.urls import path
from . import views

app_name = 'production'

urlpatterns = [

    path('', views.production, name = 'production'),
    #REPORT
    path('report/', views.report_shift, name = 'report'),
    path('report/<int:n_shift>/', views.report_view, name = 'report_shift'),
    path('report/list/', views.report_list, name = 'report_list'),
    #HOLIDAY REQUEST
    path('holiday_request/',views.holiday_request, name = 'holiday_request'),
    path('holiday_request/<int:request_id>/', views.h_request_pdf, name = 'h_request_pdf'),
    path('report/list/<str:day_1>/<str:day_2>/', views.report_list_pdf, name = 'report_list_pdf'),
    #TASK
    path('task_list/', views.task_list, name = 'task_list'),
    path('task_list/done/<str:pk>/', views.done_task, name = 'done_task'),
    path('task_list/delete/<str:pk>/', views.delete_task, name = 'delete_task'),
    path('done_today/', views.task_done_today, name = 'task_done_today'),
    path('done_last_week/', views.task_done_last_week, name = 'task_done_last_week'),
    #API
    path('api/', views.apioverview, name = 'api_view'),
    path('api/report-list/', views.reports_api, name = 'api_reports'),
    path('api/report-list/<str:pk>/', views.single_report_api, name = 'single_api_report'),
    path('api/report-list-json/', views.reports_api_json, name = 'api_reports_json'),
    path('api/report-list-json/<str:pk>/', views.single_report_api_json, name  =  'single_api_report_json'),
    path('api/redis-json/', views.redis_dict_json, name  =  'redis_dict_json'),
            ]

resume/urls.py
from django.urls import path
from . import views

app_name = 'resume'

urlpatterns = [
    path('', views.home, name='home'),
    path('about_me/', views.about_me, name='about_me'),
    path('education/', views.education, name='education'),
    path('expirience/', views.expirience, name='expirience'),
    path('website/', views.website, name='website'),
    path('contact/', views.contact, name='contact'),
    path('skills/', views.skills, name = 'skills'),
    path('back-end/', views.back, name = 'back'),
    path('skills/<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name = 'blog_detail'),
    path('skills/tag/<slug:tag_slug>/', views.skills, name='post_list_by_tag'),
    path('api/', views.api_list, name='api_list'),

    

            ]

resume/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from ckeditor.fields import RichTextField


class PublishedManager(models.Manager):

    def get_queryset(self):
        return super(PublishedManager,self).get_queryset().filter(status='published')

class Post(models.Model):

    STATUS_CHOICES = (('draft', 'Draft'), ('published', 'Published'),)
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User,on_delete=models.CASCADE, related_name='blog_posts')
    body=RichTextField(blank=True, null = True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse('resume:blog_detail', args = [self.publish.year, self.publish.strftime('%m'), self.publish.strftime('%d'), self.slug])

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title     

class Attribute(models.Model):
    name = models.CharField(max_length=20, blank=False, null=False)
    text = RichTextField(blank=False, null=False) 

    def __str__(self):
        return self.name  

resume/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Attribute
from taggit.models import Tag
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.utils import timezone
import redis
import inspect

r = redis.StrictRedis(port =6379  ,host ='localhost' ,db = 0)
TODAY = str(timezone.now().date())
 

def home(request):
    r.incr(inspect.currentframe().f_code.co_name +":"+ TODAY)
    return render(request, 'main.html',{} )

def education(request):
    data = Attribute.objects.get(name='Education')
    context = {'selected':'Education','data':data}
    r.incr(inspect.currentframe().f_code.co_name )
    return render(request, 'education.html',context)

def expirience(request):
    data = Attribute.objects.get(name='Expirience')
    context = {'selected':'Expirience','data':data}
    r.incr(inspect.currentframe().f_code.co_name +":"+ TODAY)
    return render(request, 'expirience.html',context)

def about_me(request):
    data = Attribute.objects.get(name='About_me')
    context = {'selected':'About_me','data':data}
    r.incr(inspect.currentframe().f_code.co_name +":"+ TODAY)
    return render(request, 'about_me.html',context)

def back(request):
    data = Attribute.objects.get(name='Back-end')
    context = {'selected':'Back','data':data}
    r.incr(inspect.currentframe().f_code.co_name +":"+ TODAY)
    return render(request, 'back-end.html',context)

def website(request):
    data = Attribute.objects.get(name='Website')
    context = {'selected':'Website','data':data}
    r.incr(inspect.currentframe().f_code.co_name +":"+ TODAY)
    return render(request, 'website.html',context)

def contact(request):
    data = Attribute.objects.get(name='Contact')
    context = {'selected':'Contact','data':data}
    r.incr(inspect.currentframe().f_code.co_name +":"+ TODAY)
    return render(request, 'contact.html',context)

def api_list(request):
    context = {'selected':'Api'}
    r.incr(inspect.currentframe().f_code.co_name +":"+ TODAY)
    return render(request, 'api.html',context)


def post_detail(request, year, month, day, post):
    print(request)
    post = get_object_or_404(Post, slug = post, status = 'published', publish__year = year, publish__month = month, publish__day = day)
    print(post)
    template = 'blog_detail.html'
    context = {'post': post}
    r.incr(inspect.currentframe().f_code.co_name +":"+ TODAY)
    return render(request, template, context)

def skills(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 3) 
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    context = {'page': page, 'posts': posts, 'tag':tag,'selected':'Skills'}
    r.incr(inspect.currentframe().f_code.co_name +":"+ TODAY)
    return render(request, 'skills.html', context )

resume/templates/about_me.html
{% extends "base.html" %}
{% block content %}
<div class='education'>
    {{ data.text|safe}}
</div>
{% endblock %}
{% block title %} {{ data.name}} {% endblock %}

resume/templates/api.html
{% extends "base.html" %}
{% block content %}
<div class='education'>
<ul>
    <li><a href="{% url 'production:single_api_report' 2958 %}">Example simple report  API</a></li><br><br>
    <li><a href="{% url 'production:api_reports' %}">Example simple reports API</a></li><br><br>
    <li><a href="{% url 'production:single_api_report_json' 3000 %}">Example simple API JSON report </a></li><br><br>
    <li><a href="{% url 'production:redis_dict_json'  %}">Visited my website REDIS </a></li><br><br>
    <li><a href="#">More will be soon </a></li><br><br>
</ul>
</div>
{% endblock %}
{% block title %} {{ data.name}} {% endblock %}

resume/templates/back-end.html
{% extends "base.html" %}
{% block content %}
<div class='expirience'>
    <h1 style="color:yellow">{{ data.text|safe}}</h1>
</div>
{% endblock %}
{% block title %} {{ data.name}} {% endblock %}

resume/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<link href="{% static "css/styleP.css" %}" rel="stylesheet">
<title>
{% block title %} {% endblock %}
</title>
</head>
<body>
    <header>
        <div class="logo">
               <a href="{%url "resume:home"%}">KZ resume</a>
        </div>
        <div class="main">
            <ul>
                <li {% if selected == 'Education' %}  class="active" {% endif %}><a href="{% url "resume:education" %}">Education</a></li>
                <li {% if selected == 'Expirience' %} class="active" {% endif %}><a href="{% url "resume:expirience" %}">Expirience</a></li>
                <li {% if selected == 'Skills' %}     class="active" {% endif %}><a href="{% url "resume:skills" %}">Skills and work</a></li>
                <li {% if selected == 'About_me' %}   class="active" {% endif %}><a href="{% url "resume:about_me" %}">About me</a></li>
                <li {% if selected == 'Back' %}       class="active" {% endif %}><a href="{% url "resume:back" %}">Back-end</a></li>
                <li {% if selected == 'Website' %}    class="active" {% endif %}><a href="{% url "resume:website" %}">Website</a></li>
                <li {% if selected == 'Contact' %}    class="active" {% endif %}><a href="{% url "resume:contact" %}">Contact</a></li>
                <li {% if selected == 'Api' %}    class="active" {% endif %}><a href="{% url "resume:api_list" %}">API</a></li>
                <li><a href="{% url "production:production" %}">Projects</a></li>
            </ul>
        </div>
        {% block content %} {% endblock %}
    </header>

</body>
</html>

resume/templates/blog_detail.html
{% extends "base.html" %}

{% block content %}
<div class="detail">
<h1>{{ post.title }}</h1>
<br>
{{ post.body|safe }}
</div>
{% endblock %}

{% block title %}{{ post.title }}{% endblock %}

resume/templates/contact.html
{% extends "base.html" %}
{% block content %}
<div class='contact'>
    {{ data.text|safe}}
</div>
{% endblock %}
{% block title %} {{ data.name}} {% endblock %}

resume/templates/education.html
{% extends "base.html" %}
{% block content %}
<div class='education'>
    {{ data.text|safe}}
</div>
{% endblock %}
{% block title %} {{ data.name}} {% endblock %}

resume/templates/expirience.html
{% extends "base.html" %}
{% block content %}
<div class='education'>
    {{ data.text|safe}}
</div>
{% endblock %}
{% block title %} {{ data.name}} {% endblock %}

resume/templates/main.html
{% extends "base.html" %}
{% block content %}
<div class='title'>
    <h1>Zawisza Karol</h1>
    <h2>MSc in Electrical Engineering<br/>
         specialization Automation</h2>
</div>
{% endblock %}
{% block title %} KZ_resume {% endblock %}

resume/templates/pagination.html
<div class="pagination">
        <br>
    {% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
</div>

resume/templates/skills.html
{% extends 'base.html' %}
{% block content %}
<div class="skills">
<h1 style="text-align: center;">Skills and work</h1>
<ul>
    <li><a href="/cv/skills/tag/automation/">Automation</a></li>
    <li><a href="/cv/skills/tag/cad/">&nbsp&nbspCAD&nbsp</a></li>
    <li><a href="/cv/skills/tag/django/">Django</a></li>
    <li><a href="/cv/skills/tag/english/">English</a></li>
    <li><a href="/cv/skills/tag/electric/">Electric</a></li>
    <li><a href="/cv/skills/tag/linux/">Linux</a></li>
    <li><a href="/cv/skills/tag/python/">Python</a></li>
    <li style="float:right"><a class="active" href="/cv/skills/">&nbspAll&nbsp</a></li>
  </ul>
<br>
<br>

<br>
{% for post in posts %}
<div class="post">
<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
<br><br>
{{ post.body|truncatewords:40|safe }}
</div>

{% endfor %}
<div style="align-items: center;">
{% include "pagination.html" with page=posts %}
</div>

{% endblock %}

{% block title %} Skills {% endblock %}

resume/templates/website.html
{% extends "base.html" %}
{% block content %}
<div class='education'>
    {{ data.text|safe}}
</div>
{% endblock %}
{% block title %} {{ data.name}} {% endblock %}